created new component for teacher to view rumble as table
story-squad/classroom-rumble pull request #102
Opened 2021-06-11 00:39 UTC by LizDrumm

2021-06-11 00:40 UTC, LizDrumm reviewed
Ignore this comment- not sure how to delete it.

2021-06-11 00:44 UTC, LizDrumm reviewed
Is this wrong? I feel like it is- but it was how I got the end_time to work on the `SectionRumbleCard`

2021-06-11 16:45 UTC, bramirez96 requested changes

2021-06-11 16:45 UTC, bramirez96 commented on src/components/pages/TeacherDashboard/TeacherViewSection/SectionRumbleList/SectionRumbleCard.tsx
> +          {status !== 'Complete' && <Table.Col>{rumble.phase}</Table.Col>}
Simplify this with a ternary

2021-06-11 16:45 UTC, bramirez96 commented on src/components/pages/TeacherDashboard/TeacherViewSection/SectionRumbleList/SectionRumbleCard.tsx
> +  const newDate = new Date(rumble.end_time);
Don't declare stateless variables in the scope of a component if possible, use Luxon

2021-06-11 16:45 UTC, bramirez96 commented on src/api/Rumbles/rumbleTypes.ts
> +  end_time: Date;
Put it back for inactive phase

2021-06-11 16:45 UTC, bramirez96 commented on src/components/pages/TeacherDashboard/TeacherViewSection/SectionStudentList/SectionStudentListContainer.tsx
> +    if (!studentList && !isLoading) getStudents(section.id);
Can we check if this loads the correct students for the class? I think I was wrong we might need to revert this

2021-06-17 22:08 UTC, bramirez96 approved these changes

2021-06-17 22:09 UTC, merged