Feature/common button
story-squad/classroom-rumble pull request #51
Opened 2021-04-22 18:29 UTC by sjsussman

# Feature Title

----(ERASE THIS) Description of the feature, what does it solve?----

- [ ] task to implement the feature
- [ ] another task
- [ ] notes on existing tests or plans to test
- [ ] any known problems and plans to solve them

----(ERASE THIS) Any other thoughts...----

2021-04-22 22:07 UTC, VictorDronov submitted a review, later dismissed

2021-04-22 23:05 UTC, bramirez96 requested changes

2021-04-22 23:05 UTC, bramirez96 commented on src/components/common/Button/Button.tsx
> +        {!loading ? message : <ClipLoader />}
We need to make sure that the text and the loader render at the same height so that the size of the button never changes

2021-04-22 23:05 UTC, bramirez96 commented on src/components/common/Button/index.ts
> +export { default as Button } from './Button';
button should also be exported from the common index!

2021-04-22 23:05 UTC, bramirez96 commented on src/components/common/Button/Button.tsx
> +      <button onClick={onClick} className={buttonType}>
Need to add `htmlType, ...props` to the destructuring of the props AND need to add `type={htmlType} {...props}` to the button

2021-04-22 23:05 UTC, bramirez96 commented on src/styles/components/common/button.scss
> +button {
we're going to need this to be a custom class so that we're not overriding all default buttons

2021-04-22 23:05 UTC, bramirez96 commented on src/components/common/Button/Button.tsx
> +  const buttonType = useMemo(() => {
This useMemo is wasting resources as all it's doing is assigning an existing variable to a new variable, we will fix the classNames

2021-04-23 18:04 UTC, bramirez96 approved these changes

2021-04-23 18:04 UTC, bramirez96 commented on src/components/common/Button/Button.tsx
> +}: IButtonProps): React.ReactElement => {
this should include 
```
htmlType,
...props
```

2021-04-23 18:04 UTC, VictorDronov submitted a review, later dismissed

2021-04-23 18:05 UTC, bramirez96 submitted a review, later dismissed

2021-04-23 18:10 UTC, merged