refactored api calls to useAsync and added in load and error handling
story-squad/classroom-rumble pull request #72
Opened 2021-05-05 20:00 UTC by VictorDronov

# Api calls to useAsync

Found and refactored most of the API calls to useAsync hook 

added error handling and loading handling 

*note* Left some API calls as they were because they did multiple sets at once'

2021-05-06 22:41 UTC, bramirez96 requested changes

2021-05-06 22:41 UTC, bramirez96 commented on src/components/pages/StudentDashboard/StudentViewRumble/StudentRumbleRedirect.tsx
> +      getSubForRumble(rumble.id, user.id);
This page shouldn't use the useAsync hook because we're tracking loading states in a non-default way!

2021-05-06 22:41 UTC, bramirez96 commented on src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/ViewSubmission/ViewSubmissionContainer.tsx
> +  ) : // This right?? /
I would leave it as it was before I think

2021-05-06 22:41 UTC, bramirez96 commented on src/components/pages/TeacherDashboard/TeacherViewRumble/RumbleStudentList/RumbleStudentListContainer.tsx
> +  ) : (
We should have an error or a list at this point, we don't actually need to check the loading state here.

2021-05-06 22:41 UTC, bramirez96 commented on src/components/pages/TeacherDashboard/TeacherViewRumble/TeacherViewRumbleContainer.tsx
> +
This hook doesn't need a custom setter, drop the prompt state on line 13 and remove the custom setter. Get the prompt from the 3rd value in the hook

2021-05-06 22:41 UTC, bramirez96 commented on src/components/pages/StudentDashboard/StudentViewRumble/StudentRumbleRedirect.tsx
> +    setter: setFeedbackComplete,
This one doesn't need a setter either. The state value is not initialized on line 23 and the setter is never being used elsewhere.

2021-05-06 22:41 UTC, bramirez96 commented on src/components/pages/TeacherDashboard/TeacherViewSubmission/RenderTeacherViewSubmission.tsx
>        </div>
Good catch!

2021-05-08 02:37 UTC, VictorDronov commented on src/components/pages/StudentDashboard/StudentViewRumble/StudentRumbleRedirect.tsx
> +    setter: setFeedbackComplete,
This does not matter anymore i changed it back to the older way.

2021-05-11 19:39 UTC, bramirez96 approved these changes

2021-05-11 19:40 UTC, merged