Refactor/dynamic feedback questions
story-squad/classroom-rumble pull request #93
Opened 2021-05-25 21:03 UTC by AprilAshby

# Refactor
## Dynamically renders feedback questions

2021-05-25 21:32 UTC, bramirez96 requested changes

2021-05-25 21:32 UTC, bramirez96 commented on src/components/common/CouldNotLoad/CouldNotLoad.tsx
> +import ufo_cow from '../../../assets/img/Alien.svg';
It's officially lowercase

2021-05-27 21:44 UTC, bramirez96 approved these changes

2021-05-27 21:45 UTC, LizDrumm approved these changes

2021-05-27 21:45 UTC, VictorDronov approved these changes

2021-05-27 21:48 UTC, merged